#!/usr/bin/env bash
# TAPPaaS Module: nextcloud-hpb — Installation
#
# Nextcloud Talk High-Performance Backend (nextcloud-spreed-signaling + NATS loopback)
#
# Creates the nextcloud-hpb VM on tappaas2 and wires it up to both Nextcloud and coturn
# so no manual steps are needed beyond creating a DNS A record.
#
# Secret planes:
#   Runtime:    /var/lib/nextcloud-hpb/secrets/ on the HPB VM (generated by NixOS hpb-init-secrets on first boot)
#   Management: /home/tappaas/secrets/nextcloud-hpb.env on tappaas-cicd (written here at install time)
#   coturn dep: /home/tappaas/secrets/coturn.env on tappaas-cicd (written by coturn/install.sh)
#
# Usage: ./install.sh <vmname>
# Example: ./install.sh nextcloud-hpb

. /home/tappaas/bin/install-vm.sh

# run the update script as all update actions are also needed at install time
. ./update.sh

HPB_HOST="nextcloud-hpb.srv.internal"
NEXTCLOUD_HOST="nextcloud.srv.internal"
PROXY_DOMAIN="$(get_config_value 'proxyDomain')"
HPB_HOST_PART="${PROXY_DOMAIN%%.*}"
HPB_DOMAIN_PART="${PROXY_DOMAIN#*.}"
MGMT_SECRETS="/home/tappaas/secrets/nextcloud-hpb.env"
COTURN_MGMT_SECRETS="/home/tappaas/secrets/coturn.env"
# Runtime secrets directory — must match secretsDir in nextcloud-hpb.nix
HPB_SECRETS_DIR="/var/lib/nextcloud-hpb/secrets"

# ── Read HPB_SECRET from runtime plane → save to management plane ────────────
echo ""
info "${BOLD}Reading HPB secrets from VM…${CL}"

HPB_SECRET=$(ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=no \
    "tappaas@${HPB_HOST}" \
    "sudo cat ${HPB_SECRETS_DIR}/hpb-secret 2>/dev/null" || true)

if [[ -n "${HPB_SECRET}" ]]; then
    upsert_secret "${MGMT_SECRETS}" "HPB_SECRET" "${HPB_SECRET}"
    info "  HPB_SECRET saved to management plane (${MGMT_SECRETS})."
else
    die "Could not read HPB_SECRET from ${HPB_SECRETS_DIR}/hpb-secret — NixOS config may not have been deployed (hpb-init-secrets did not run)"
fi

# ── Sync COTURN_SECRET from management plane → HPB VM (runtime) ──────────────
echo ""
info "${BOLD}Syncing coturn TURN secret to HPB VM…${CL}"

COTURN_SECRET=""
if [[ -f "${COTURN_MGMT_SECRETS}" ]]; then
    COTURN_SECRET=$(grep '^COTURN_SECRET=' "${COTURN_MGMT_SECRETS}" | cut -d= -f2- || true)
fi

if [[ -z "${COTURN_SECRET}" ]]; then
    die "COTURN_SECRET not found in ${COTURN_MGMT_SECRETS} — ensure coturn is installed before nextcloud-hpb"
fi

ssh -o BatchMode=yes -o ConnectTimeout=15 "tappaas@${HPB_HOST}" \
    "printf '%s\n' '${COTURN_SECRET}' \
       | sudo tee ${HPB_SECRETS_DIR}/turn-secret > /dev/null \
     && sudo chown nextcloud-spreed-signaling:nextcloud-spreed-signaling \
          ${HPB_SECRETS_DIR}/turn-secret \
     && sudo chmod 400 ${HPB_SECRETS_DIR}/turn-secret \
     && sudo systemctl restart nextcloud-spreed-signaling.service" \
    || die "Failed to sync TURN secret to HPB VM"
info "  TURN secret synced to runtime plane; nextcloud-spreed-signaling restarted."

# ── Configure Nextcloud Talk HPB signaling backend ───────────────────────────
echo ""
info "${BOLD}Configuring Nextcloud Talk signaling backend…${CL}"

ssh -o BatchMode=yes -o ConnectTimeout=15 "tappaas@${NEXTCLOUD_HOST}" \
    "printf 'HPB_SECRET=%s\n' '${HPB_SECRET}' \
       | sudo tee /etc/secrets/hpb.env > /dev/null \
     && sudo chmod 600 /etc/secrets/hpb.env \
     && sudo chown root:root /etc/secrets/hpb.env" \
    || die "Failed to write /etc/secrets/hpb.env to Nextcloud VM"
info "  /etc/secrets/hpb.env written to Nextcloud VM."

ssh -o BatchMode=yes -o ConnectTimeout=15 "tappaas@${NEXTCLOUD_HOST}" \
    "sudo systemctl restart nextcloud-configure-hpb.service 2>&1 || true" && \
    info "  nextcloud-configure-hpb.service triggered." || \
    warn "  Failed to trigger nextcloud-configure-hpb.service — reboot Nextcloud VM to apply."

# ── Internal DNS override via OPNsense (split-horizon) ───────────────────────
# Maps ${PROXY_DOMAIN} → 10.2.10.1 (SRV zone gateway) so Nextcloud
# and other internal hosts resolve the public domain to the local Caddy proxy
# instead of the WAN IP (which hairpins back through the ISP router).
echo ""
info "${BOLD}Adding internal DNS override in OPNsense…${CL}"

if dns-manager --no-ssl-verify add "${HPB_HOST_PART}" "${HPB_DOMAIN_PART}" "10.2.10.1" \
        --description "nextcloud-hpb internal split-horizon override"; then
    info "  ${PROXY_DOMAIN} → 10.2.10.1 added to OPNsense DNS."
else
    warn "  dns-manager failed — add the override manually in OPNsense:"
    warn "    Host: ${HPB_HOST_PART}   Domain: ${HPB_DOMAIN_PART}   IP: 10.2.10.1"
fi

echo ""
info "${GN}✓${CL} nextcloud-hpb installation completed successfully."
echo ""
info "  Signaling URL : wss://${PROXY_DOMAIN}/spreed"
info ""
info "  ${BOLD}ACTION REQUIRED — Public DNS record only:${CL}"
info "    ${PROXY_DOMAIN} → <WAN IP>  (external clients, e.g. 5G)"
info "    (Internal override already added to OPNsense above)"
