#!/usr/bin/env bash
# TAPPaaS Module: coturn — Installation
#
# coturn TURN/STUN server for Nextcloud Talk WebRTC audio/video calls.
#
# Creates the coturn VM in Proxmox and applies initial configuration.
# It assumes that you are in the install directory.
#
# Secret planes:
#   Runtime:    /etc/secrets/coturn.env on the coturn VM (generated by NixOS on first boot)
#   Management: /home/tappaas/secrets/coturn.env on tappaas-cicd (written here at install time)
#
# Usage: ./install.sh <vmname>
# Example: ./install.sh coturn

set -euo pipefail

. /home/tappaas/bin/common-install-routines.sh

# Derive public domain from platform configuration
GLOBAL_CONFIG="/home/tappaas/config/configuration.json"
BASE_DOMAIN="$(jq -r '.tappaas.domain' "${GLOBAL_CONFIG}")"
COTURN_VMNAME="$(jq -r '.vmname' "$(dirname "${BASH_SOURCE[0]}")/coturn.json")"
COTURN_DOMAIN="${COTURN_VMNAME}.${BASE_DOMAIN}"

COTURN_HOST="coturn.dmz.internal"
NEXTCLOUD_HOST="nextcloud.srv.internal"
readonly MGMT_SECRETS="/home/tappaas/secrets/coturn.env"

# ── Read COTURN_SECRET from runtime plane → save to management plane ─────────
echo ""
info "${BOLD}Reading coturn secret…${CL}"

COTURN_SECRET=$(ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=no \
    "tappaas@${COTURN_HOST}" \
    "sudo grep '^COTURN_SECRET=' /etc/secrets/coturn.env | cut -d= -f2-") || {
    warn "Could not read COTURN_SECRET from ${COTURN_HOST} — configure manually."
    COTURN_SECRET=""
}

if [[ -n "${COTURN_SECRET}" ]]; then
    upsert_secret "${MGMT_SECRETS}" "COTURN_SECRET" "${COTURN_SECRET}"
    info "  COTURN_SECRET saved to management plane (${MGMT_SECRETS})."
else
    warn "  COTURN_SECRET unavailable — management plane not updated."
fi

# ── Push COTURN_SECRET to Nextcloud (consumer) ───────────────────────────────
echo ""
info "${BOLD}Configuring coturn secret on Nextcloud…${CL}"

if [[ -n "${COTURN_SECRET}" ]]; then
    info "  Writing coturn.env to Nextcloud VM…"
    ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=no "tappaas@${NEXTCLOUD_HOST}" \
        "printf 'COTURN_SECRET=%s\n' '${COTURN_SECRET}' | sudo tee /etc/secrets/coturn.env > /dev/null && \
         sudo chmod 600 /etc/secrets/coturn.env && \
         sudo chown root:root /etc/secrets/coturn.env" && \
        info "  /etc/secrets/coturn.env written." || \
        warn "  Failed to write /etc/secrets/coturn.env on Nextcloud VM."

    info "  Triggering nextcloud-configure-talk.service…"
    ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=no "tappaas@${NEXTCLOUD_HOST}" \
        "sudo systemctl restart nextcloud-configure-talk.service 2>&1 || true" && \
        info "  nextcloud-configure-talk.service triggered." || \
        warn "  Failed to trigger nextcloud-configure-talk.service — reboot the VM to apply."
else
    warn "  Skipping Nextcloud coturn setup — COTURN_SECRET unavailable."
fi

# ── Auto-detect WAN IP → write to coturn VM + management plane ───────────────
echo ""
info "${BOLD}Detecting WAN IP from OPNsense…${CL}"

CRED_FILE="/home/tappaas/.opnsense-credentials.txt"
FIREWALL="firewall.mgmt.internal"
WAN_IP=""

if [[ -f "$CRED_FILE" ]]; then
    OPNSENSE_TOKEN=$(sed -n '1p' "$CRED_FILE")
    OPNSENSE_SECRET=$(sed -n '2p' "$CRED_FILE")

    WAN_IP=$(curl -sk --max-time 10 \
        -u "${OPNSENSE_TOKEN}:${OPNSENSE_SECRET}" \
        "https://${FIREWALL}/api/interfaces/overview/interfacesInfo" \
        | jq -r '.rows[] | select(.identifier == "wan") | .ipv4 // empty' \
        | cut -d/ -f1 || true)
fi

if [[ -n "${WAN_IP}" ]]; then
    info "  Detected WAN IP: ${WAN_IP}"
    info "  Writing COTURN_EXTERNAL_IP to coturn VM…"
    ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=no "tappaas@${COTURN_HOST}" \
        "sudo sed -i 's/^COTURN_EXTERNAL_IP=.*/COTURN_EXTERNAL_IP=${WAN_IP}/' /etc/secrets/coturn.env && \
         sudo systemctl restart coturn.service" && \
        info "  COTURN_EXTERNAL_IP=${WAN_IP} set and coturn restarted." || \
        warn "  Failed to update COTURN_EXTERNAL_IP on coturn VM — set it manually."
    upsert_secret "${MGMT_SECRETS}" "COTURN_EXTERNAL_IP" "${WAN_IP}"
    info "  COTURN_EXTERNAL_IP saved to management plane."
else
    warn "  Could not detect WAN IP from OPNsense — set it manually:"
    warn "    ssh tappaas@${COTURN_HOST}"
    warn "    sudo sed -i 's/COTURN_EXTERNAL_IP=/COTURN_EXTERNAL_IP=<YOUR-WAN-IP>/' /etc/secrets/coturn.env"
    warn "    sudo systemctl restart coturn.service"
fi

# ── Remaining manual steps ────────────────────────────────────────────────────
echo ""
warn "Ensure OPNsense has the following (not configured automatically):"
warn "  - NAT rule: WAN:3478 (UDP+TCP) -> coturn DMZ IP:3478"
warn "  - NAT rule: WAN:49152-65535 (UDP) -> coturn DMZ IP:49152-65535"
warn "  - DNS A record: ${COTURN_DOMAIN} -> public WAN IP"

echo ""
info "${GN}✓${CL} coturn installation completed successfully."
