# ----------------------------------------
# TAPPaaS Community Module
# Name:    Forgejo — self-hosted Git service (Gitea fork)
# Type:    NixOS VM
# Zone:    srv
# Version: 9.0.3
# Date:    2026-06-01
# Author:  @ErikDaniel007
# License: MIT (Forgejo upstream)
# ----------------------------------------

{ config, pkgs, lib, ... }:

let
  versions = {
    forgejo    = "9.0.3";
    forgejoApp = pkgs.forgejo;  # resolved from nixpkgs — pin overrideAttrs if needed
  };
in
{
  imports = [ /etc/nixos/hardware-configuration.nix ];

  # === Boot ===
  boot.loader.systemd-boot.enable    = lib.mkDefault true;
  boot.loader.efi.canTouchEfiVariables = lib.mkDefault true;
  boot.growPartition                 = lib.mkDefault true;

  system.stateVersion = "25.05";

  # === Networking ===
  networking = {
    hostName            = lib.mkDefault "forgejo";
    networkmanager.enable = true;
    # Match ethernet by type — interface name varies across clone generations
    networkmanager.ensureProfiles.profiles.tappaas-ethernet = {
      connection = {
        id                   = "tappaas-ethernet";
        type                 = "ethernet";
        autoconnect          = "true";
        autoconnect-priority = "100";
      };
      ipv4.method = "auto";
      ipv6 = { method = "auto"; addr-gen-mode = "default"; };
    };
    # NixOS in-guest firewall — allow SSH, Forgejo web, and git-SSH
    firewall.allowedTCPPorts = [ 22 3000 ];
  };

  # Disable systemd-networkd (NetworkManager owns networking)
  systemd.network.enable            = lib.mkForce false;
  systemd.network.wait-online.enable = lib.mkForce false;

  # === Proxmox integration ===
  systemd.services."serial-getty@ttyS0" = {
    enable      = true;
    wantedBy    = [ "getty.target" ];
    serviceConfig.Restart = "always";
  };
  services.qemuGuest.enable = true;
  services.cloud-init = {
    enable         = true;
    network.enable = false;
  };

  time.timeZone = lib.mkDefault "Europe/Amsterdam";

  # === Users ===
  users.users.tappaas = {
    isNormalUser  = true;
    extraGroups   = [ "wheel" "networkmanager" ];
    shell         = pkgs.bash;
  };

  security.sudo.wheelNeedsPassword = false;

  services.openssh = {
    enable   = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin        = "no";
    };
  };
  programs.ssh.startAgent = true;

  # === Forgejo service ===
  services.forgejo = {
    enable   = true;
    package  = versions.forgejoApp;

    settings = {
      DEFAULT = {
        APP_NAME = lib.mkDefault "Forgejo";
      };

      server = {
        HTTP_PORT        = lib.mkDefault 3000;
        SSH_PORT         = lib.mkDefault 22;
        START_SSH_SERVER = lib.mkDefault false;  # Use system OpenSSH
        # ROOT_URL, DOMAIN and SSH_DOMAIN: set via admin panel or app.ini override
        # after first login. Do not hardcode — value depends on operator's domain.
      };

      database = {
        # SQLite is the default backend — sufficient for single-team use.
        # Switch to postgres if concurrent load exceeds 50 users:
        #   DB_TYPE  = "postgres";
        #   HOST     = "127.0.0.1:5432";
        #   NAME     = "forgejo";
        #   USER     = "forgejo";
        DB_TYPE = lib.mkDefault "sqlite3";
        PATH    = lib.mkDefault "/var/lib/forgejo/data/forgejo.db";
      };

      repository = {
        ROOT = lib.mkDefault "/var/lib/forgejo/repositories";
      };

      service = {
        DEFAULT_ORG_VISIBILITY = lib.mkDefault "private";
        # DISABLE_REGISTRATION and INSTALL_LOCK are set via the web installer on
        # first boot. Do not configure here — installer handles greenfield bootstrap.
      };

      security = {
        SECRET_KEY     = lib.mkDefault "";  # Generated by installer on first boot
        INTERNAL_TOKEN = lib.mkDefault "";  # Same
      };

      mailer = {
        ENABLED = lib.mkDefault false;  # Configure in INSTALL.md §Post-install
      };

      log = {
        MODE  = lib.mkDefault "file";
        LEVEL = lib.mkDefault "Info";
      };

      webhook = {
        ALLOWED_HOST_LIST = lib.mkDefault "loopback,private";
      };
    };
  };

  # === Data directories ===
  systemd.tmpfiles.rules = [
    "d /var/lib/forgejo/repositories 0750 git git -"
    "d /var/backup/forgejo            0700 git git -"
  ];

  # === Backup: daily dump of repositories + SQLite ===
  systemd.services.forgejo-backup = {
    description = "Forgejo daily backup";
    after       = [ "forgejo.service" ];
    serviceConfig = {
      Type    = "oneshot";
      User    = "git";
      ExecStart = pkgs.writeShellScript "forgejo-backup" ''
        set -euo pipefail
        DEST=/var/backup/forgejo/forgejo-$(date +%F)
        mkdir -p "$DEST"
        # Repositories (bare git)
        ${pkgs.rsync}/bin/rsync -a /var/lib/forgejo/repositories/ "$DEST/repositories/"
        # SQLite DB — pause Forgejo write-ahead log with PRAGMA
        ${pkgs.sqlite}/bin/sqlite3 /var/lib/forgejo/data/forgejo.db \
          "VACUUM INTO '$DEST/forgejo.db.bak';"
        echo "Backup complete: $DEST"
      '';
    };
  };
  systemd.timers.forgejo-backup = {
    description         = "Daily Forgejo backup at 03:00";
    wantedBy            = [ "timers.target" ];
    timerConfig.OnCalendar = "*-*-* 03:00:00";
    timerConfig.Persistent = true;
  };

  # === Backup rotation (30 days) ===
  systemd.services.forgejo-cleanup = {
    description = "Remove Forgejo backups older than 30 days";
    serviceConfig = {
      Type    = "oneshot";
      User    = "root";
      ExecStart = pkgs.writeShellScript "forgejo-cleanup" ''
        ${pkgs.findutils}/bin/find /var/backup/forgejo -maxdepth 1 -type d -mtime +30 -exec rm -rf {} +
      '';
    };
  };
  systemd.timers.forgejo-cleanup = {
    description         = "Monthly Forgejo backup cleanup";
    wantedBy            = [ "timers.target" ];
    timerConfig.OnCalendar = "monthly";
    timerConfig.Persistent = true;
  };

  # === System packages ===
  environment.systemPackages = with pkgs; [
    vim wget curl htop git rsync sqlite
  ];

  # === Nix ===
  nix.settings.trusted-users        = [ "root" "@wheel" ];
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nixpkgs.config.allowUnfree        = true;

  nix.gc = {
    automatic = true;
    dates     = "weekly";
    options   = "--delete-older-than 30d";
  };
}